on: [push, repository_dispatch]
name: Build and deploy on push
jobs:
  build:
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        repo: tcheinen/resume
        path: .
    - name: Download writeup-export
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: rust.yml
        repo: tcheinen/writeup-export
        path: .
    - name: fetch writeups!
      run: git clone https://github.com/tcheinen/ctf-writeups
    - name: build writeups
      run: |
        chmod +x /writeup-export/writeup-export
        ./writeup-export/writeup-export -i ctf-writeups -o content
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: .
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}
